# Generated by Django 4.1.2 on 2023-04-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='inOfferta',
            field=models.DateTimeField(blank=True, default='No', null=True),
        ),
    ]
