# Generated by Django 5.0.1 on 2024-08-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="citta",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
