# Generated by Django 5.0.1 on 2024-10-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_activity_citta"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prodotto",
            options={"ordering": ("-prezzo", "genere", "descrizione")},
        ),
        migrations.AlterField(
            model_name="prodotto",
            name="inOfferta",
            field=models.DateField(blank=True, null=True),
        ),
    ]
