# Generated by Django 4.1.2 on 2023-04-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_prodotto_inofferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='inOfferta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
