# Generated by Django 5.0.1 on 2024-10-26 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_prezzo_activity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ("name", "strada")},
        ),
    ]
