# Generated by Django 5.0.1 on 2024-07-29 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_zona"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prodotto",
            options={"ordering": ("prezzo", "genere", "descrizione")},
        ),
        migrations.AddField(
            model_name="prodotto",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.activity",
            ),
        ),
    ]
