# Generated by Django 5.0.1 on 2024-10-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_prodotto_options_alter_prodotto_inofferta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="logo",
        ),
        migrations.AddField(
            model_name="activity",
            name="imageLogo",
            field=models.ImageField(blank=True, upload_to="media/prodotti/%Y/%m/%d"),
        ),
    ]
