# Generated by Django 5.0.1 on 2024-07-29 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_prodotto_options_prodotto_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="activity",
        ),
    ]
