# Generated by Django 5.0.1 on 2024-10-27 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_activity_options"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="prezzo",
            index_together=set(),
        ),
    ]
