# Generated by Django 5.0.1 on 2024-10-27 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_prezzo_index_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prezzo",
            name="prodotto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prezzo",
                to="main.prodotto",
            ),
        ),
    ]
