# Generated by Django 5.0.1 on 2024-07-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_remove_activity_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="loghi"),
        ),
    ]
