# Generated by Django 5.0.1 on 2024-10-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_prezzo_prodotto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="prodotto",
            field=models.ManyToManyField(blank=True, null=True, to="main.prodotto"),
        ),
    ]
