# Generated by Django 5.0.1 on 2024-10-28 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_activity_prodotto"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="prezzo",
            index_together={("prodotto", "prezzo")},
        ),
    ]
