# Generated by Django 5.0.1 on 2024-10-28 07:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_prezzo_index_together"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="prezzo",
            index_together={("prodotto", "prezzo", "activity")},
        ),
    ]
