# Generated by Django 5.0.1 on 2024-10-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_prezzo_index_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="prodotto",
            field=models.ManyToManyField(to="main.prodotto"),
        ),
    ]
