# Generated by Django 5.0.1 on 2024-10-29 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_activity_prodotto"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="prodotto",
            index_together=set(),
        ),
    ]
