# Generated by Django 5.0.1 on 2024-10-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_prodotto_index_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="prodotto",
            field=models.ManyToManyField(null=True, to="main.prodotto"),
        ),
    ]
