# Generated by Django 5.0.1 on 2024-10-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_alter_activity_prodotto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prezzo",
            name="prezzo",
            field=models.DecimalField(
                blank=True, decimal_places=2, default="0.00", max_digits=10, null=True
            ),
        ),
    ]
