# Generated by Django 5.0.1 on 2024-10-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_alter_prezzo_prezzo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="prodotto",
            field=models.ManyToManyField(to="main.prodotto"),
        ),
    ]
