# Generated by Django 5.0.1 on 2024-11-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_alter_activity_prodotto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prodotto",
            options={"ordering": ("creato",)},
        ),
        migrations.RemoveField(
            model_name="activity",
            name="prodotto",
        ),
        migrations.RemoveField(
            model_name="prodotto",
            name="genere",
        ),
        migrations.AddField(
            model_name="prodotto",
            name="genere",
            field=models.ManyToManyField(related_name="prodotti", to="main.genere"),
        ),
    ]
