# Generated by Django 5.0.1 on 2024-11-10 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_alter_prodotto_options_remove_activity_prodotto_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genere",
            options={"ordering": ("name",)},
        ),
    ]
