# Generated by Django 5.0.1 on 2024-11-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_alter_genere_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genere",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
    ]
