# Generated by Django 5.0.1 on 2024-11-19 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_alter_genere_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prezzo",
            name="activity",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supermarkets",
                to="main.activity",
            ),
            preserve_default=False,
        ),
    ]
