# Generated by Django 5.0.1 on 2024-11-19 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_alter_prezzo_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prezzo",
            name="prodotto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prezzo",
                to="main.prodotto",
            ),
        ),
    ]
