# Generated by Django 5.0.1 on 2024-11-19 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_alter_prezzo_prodotto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prezzo",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supermarkets",
                to="main.activity",
            ),
        ),
        migrations.AlterField(
            model_name="prezzo",
            name="prezzo",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=10),
        ),
    ]
